Various improvements
alfred-hodler/rust-coldcard pull request #4
Opened 2022-10-15 08:00 UTC by cloudhead

Hey there, I've been using a fork of your library but thought I would propose the changes here, since it might benefit more people. Each commit should describe the change.

2022-10-15 10:01 UTC, alfred-hodler requested changes
Thank you for this PR! Almost everything looks solid, I just have a few minor points that I'd like addressed, including one potential regression.

Otherwise, this is almost good to go :rocket: 

If you'd like an immediate crates.io release, please bump the patch portion of the version.

2022-10-15 10:03 UTC, alfred-hodler commented
> We should eventually also replace aes-ctr with aes, since the former is deprecated.

Agreed. I picked an older version simply because the API was cleaner and easier to use, but this change needs to be made for security reasons.

2022-10-15 10:43 UTC, cloudhead commented on coldcard/src/firmware.rs
> +            if (0..elements).next().is_some() {
I was also confused at first, but if you look at the loop, there is a return statement at the end (and no `continue` statement), so it only loops once. Perhaps this points to a bug in the code?

2022-10-15 10:44 UTC, cloudhead commented on coldcard/Cargo.toml
> +linux-static-libusb = ["hidapi/linux-static-libusb"]
Yeah, can do.

2022-10-15 10:52 UTC, cloudhead commented on coldcard/Cargo.toml
> +bitcoin = { version = "0.29.1", features = ["rand"] }
I generally agree, but here's why I made this change:
1. We get to drop the `base58` dependency and use the one in `bitcoin`
2. It's almost a given that a crate importing `coldcard` is also already depending on `bitcoin`, for all the wallet-related types in there.
3. There are some places in `coldcard` that could benefit from using `bitcoin` crate types, eg. `DerivationPath` and other `bitcoin::util::bip32` functions, as well as the `Address` type which should ideally be returned from the `Coldcard::address` method. I'm sure I will encounter others.

If you don't agree with the above, I would suggest perhaps making it an optional dependency that can be enabled for conversion methods and dependency consolidation.

2022-10-15 10:54 UTC, cloudhead commented
> Agreed. I picked an older version simply because the API was cleaner and easier to use, but this change needs to be made for security reasons.

Yeah, I tried moving it over to `aes` but there were too many differences, so I think it will take a bit more work.

2022-10-15 15:07 UTC, alfred-hodler commented on coldcard/Cargo.toml
> +bitcoin = { version = "0.29.1", features = ["rand"] }
The third reason is particularly compelling. We can get rid of those custom structs by using `rust-bitcoin` types in those places.

2022-10-15 15:07 UTC, alfred-hodler commented on coldcard/src/firmware.rs
> +            if (0..elements).next().is_some() {
Clippy did the right thing. I just checked Coinkite's Python library and it's also only looking at the first offset. It appears there should always be a firmware blob at the first offset, at least the way they build their `.dfu` files, so this is fine.

2022-10-15 15:09 UTC, alfred-hodler commented
Looks good. We can replace those custom bip32 structs in a different unit of work, along with upgrading the AES crate.

2022-10-15 15:11 UTC, merged

2022-10-16 17:17 UTC, cloudhead commented
Great!